package edu.icet.com.bitezza.mapper;

import edu.icet.com.bitezza.model.dto.OrderItemDTO;
import edu.icet.com.bitezza.model.entity.Order;
import edu.icet.com.bitezza.model.entity.OrderItem;

public class OrderItemMapper {

    // DTO → Entity
    public static OrderItem toEntity(OrderItemDTO dto, Order order) {

        if (dto == null) return null;

        OrderItem item = new OrderItem();

        // id is generated by DB
        item.setProductId(dto.getProductId());
        item.setQuantity(dto.getQuantity());
        item.setPrice(dto.getPrice());

        // VERY IMPORTANT - set parent order
        item.setOrder(order);

        return item;
    }

}
